# Generated by Django 4.2.11 on 2026-05-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ali Mahmoud', help_text='Full name of the portfolio owner', max_length=255)),
                ('title', models.CharField(default='Penetration Tester & Automation Engineer', help_text='Professional title/role', max_length=255)),
                ('bio_strong', models.TextField(default='I break systems to protect them.. and build defense lines with code.', help_text='Main biography statement')),
                ('contact_phrase', models.CharField(default='No ordinary contact form. Just send a signal to:', help_text='Introduction text for contact section', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title/name', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('tech_stack', models.CharField(help_text="Comma-separated list of technologies (e.g., 'Python, Docker, Kubernetes')", max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Project image/screenshot (optional)', null=True, upload_to='projects/')),
                ('link', models.URLField(blank=True, help_text='External link to project (GitHub, demo, etc.)', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill/technology', max_length=255, unique=True)),
                ('icon_class', models.CharField(help_text="FontAwesome icon class (e.g., 'fa-python', 'fa-docker')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of the event (e.g., 2020, 2024)')),
                ('title', models.CharField(help_text='Event title/headline', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order', 'year'],
            },
        ),
    ]
