# Generated by Django 4.2.11 on 2026-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='ali@example.com', help_text='Primary contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='journey',
            field=models.TextField(blank=True, default='My path blends Linux engineering, DevOps automation, and practical cybersecurity.\nI help teams build secure infrastructure that feels smart and stable.', help_text='Short story about your journey, displayed in the About section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Personal photo for the hero section', null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default='IT Linux Engineer | DevOps Engineer | Cybersecurity Analyst', help_text='Typed subtitle line shown under the name', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text="Link to the project's GitHub repository", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True, help_text='Short project summary for the card, such as tech or results', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_strong',
            field=models.TextField(default='I build calm, resilient systems that balance security and operations.', help_text='Short one-sentence bio for the hero section'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_phrase',
            field=models.CharField(default="Let's connect by email:", help_text='Introduction text for contact section', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='External link to project demo or details (optional)', max_length=500, null=True),
        ),
    ]
