# Generated by Django 4.2.11 on 2026-05-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_profile_email_profile_journey_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL (optional)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL (optional)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL (optional)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo_text',
            field=models.CharField(default='AM', help_text="Logo/site name shown in navbar (e.g., 'AM' or 'Ali Mahmoud')", max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube profile URL (optional)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Personal photo for the hero section', max_length=255, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project image/screenshot (optional)', max_length=255, null=True, upload_to='projects/'),
        ),
    ]
