apiVersion: v1                 # API version for core Kubernetes resources
kind: ConfigMap               # This resource stores non-sensitive configuration

metadata:
  name: django-config         # Name of the ConfigMap
  namespace: django-prod      # Namespace where this ConfigMap exists

  labels:
    app: django               # Label to identify the app
    tier: backend             # Label to identify the app tier

data:

  DB_NAME: "django_k8s_db"    # Name of the PostgreSQL database
  DB_USER: "ali"              # Database username
  DB_HOST: "postgres-service" # Hostname (Kubernetes Service name for Postgres)
  DB_PORT: "5432"             # Port PostgreSQL is running on

  DEBUG: "False"              # Django debug mode (False for production)
