apiVersion: v1                 # API version for core Kubernetes resources
kind: ConfigMap               # This resource stores non-sensitive configuration

metadata:
  name: django-config         # Name of the ConfigMap
  namespace: django-prod      # Namespace where this ConfigMap exists

  labels:
    app: django               # Label to identify the app
    tier: backend             # Label to identify the app tier

data:

  POSTGRES_DB: "django_k8s_db"
  POSTGRES_USER: "ali"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

  DEBUG: "False"
