apiVersion: v1
kind: Secret

metadata:

  name: django-secret
  namespace: django-prod

  labels:
    app: django
    tier: backend


type: Opaque

data:

  DB_PASSWORD: "cm9vdA=="  # echo -n "cm9vdA==" | base64 --encode


  DJANGO_SECRET_KEY: "ZDU4ZWY0YTNmYzQ="
