apiVersion: apps/v1                         # API version for Deployments
kind: Deployment                            # Type of resource to create

metadata:                                   # Metadata about this Deployment
  name: postgres-deployment                 # Name of the Deployment
  namespace: django-prod                    # Target isolated environment
  labels:                                   # Label for the Deployment itself
    app: postgres                           # Label key and value

spec:                                       # Deployment specifications
  replicas: 1                               # Run exactly 1 pod instance

  selector:                                 # How to find the correct pods
    matchLabels:                            # Match pods with this exact label
      app: postgres                         # Target pod label to manage

  template:                                 # Template for creating new pods
    metadata:                               # Metadata for the pod
      labels:                               # Labels to put on the pod
        app: postgres                       # Pod label (matches selector above)

    spec:                                   # Technical specifications for the pod
      containers:                           # List of containers inside the pod
      - name: postgres                      # Internal name of the container
        image: postgres:15-alpine           # PostgreSQL official image name and version

        ports:                              # Network ports settings
        - containerPort: 5432               # Default internal PostgreSQL port

        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: POSTGRES_DB

        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_PASSWORD

        - name: POSTGRES_HOST_AUTH_METHOD
          value: "md5"

        volumeMounts:                       # Attach storage to container path
        - name: postgres-storage            # Name of volume link to use
          mountPath: /var/lib/postgresql/data # Directory path inside container

      volumes:                              # Define physical storage volumes
      - name: postgres-storage              # Name of volume defined for this file
        persistentVolumeClaim:              # Link volume to an active PVC
          claimName: postgres-pvc          # Name of real PVC file (File 03)
