name: DevOps CI Pipeline  # pipeline name

on:
  push:
    branches: ["first"]

  pull_request:
    branches: ["first"]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/django_app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. get code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. build all services using docker compose
      - name: Build services
        run: docker compose build

      # 3. run containers (background)
      - name: Run services
        run: docker compose up -d

      # 4. run tests inside container
      - name: Run tests
        run: docker compose exec web python manage.py test

      # 5. stop containers after test
      - name: Stop services
        run: docker compose down

      # 6. login to Docker Hub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 7. build image (final)
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      # 8. push image
      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest
